version: '3.8'

services:
   db:
      image: postgres:latest
      container_name: falqon-db
      ports:
         - "5432:5432"
      env_file:
         - .env
      environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
         - postgres-data:/var/lib/postgresql/data
volumes:
   postgres-data:
      external: false
